[package]
name = "bevy-better-events"
version = "0.1.0"
edition = "2021"
description = "better events and related objects for bevy"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"